# Generated by Django 3.0.5 on 2020-05-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Tag'),
        ),
    ]
