# Generated by Django 3.0.5 on 2020-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_breakfastorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastorder',
            name='is_needed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
