# Generated by Django 3.0.5 on 2020-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_breakfastorder_is_needed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='num_guest',
            new_name='adult',
        ),
        migrations.AddField(
            model_name='room',
            name='kid',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('OCC', 'Occupied'), ('CO', 'Check Out'), ('V', 'Vacant')], default='pending', max_length=20),
        ),
    ]
