# Generated by Django 3.0.5 on 2020-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('OCC', 'Occupied'), ('CO', 'Check Out'), ('V', 'Vacant')], default='Vacant', max_length=20),
        ),
    ]
