# Generated by Django 3.0.5 on 2020-05-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='main',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='starter',
            name='show_date',
        ),
        migrations.AddField(
            model_name='dessert',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='starter',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True),
        ),
    ]
